### ISSUE TITLE
Ritual highlighting

### ISSUE THREAD

**Issue by flying-sheep** [SamLojpur/practitioners-awakening#1]
Hia! Love the website!

I just thought it’s a bit hard to interpret which Other used which gates/offerings, since there’s no indicator. Also some exit by gates other than the one they enter from!

Maybe highlighting circles in addition to make them stop spinning would help?

**Comment by SamLojpur** [comment]
YOO hello I almost forgot about this, please don't look at the code its embarrassingly bad. How did you even find this haha

Yeah that's a good idea, I added a fix so that the gates/offerings are highlighted and the exit gate specifically is highlighted red. I don't have any better ideas for differentiating entrance from exit, but if you have a better one let me know.

**Comment by flying-sheep** [comment]
I found it linked in some Reddit discussion! I love little projects like this, I wish things like this were linked in the community, but [/r/Parahumans](https://www.reddit.com/r/Parahumans/) is super barebones with what it links.
